-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "neighborhood" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "complement" TEXT;
